### ISSUE TITLE
좋아요 버튼

### ISSUE THREAD

**Issue by chcjswo** [chcjswo/dolpic-nodejs#4]
### 이슈 사항
1) 뷰페이지에서 더블클릭시
    좋아요가 반영되지 않음
2) 더블클릭시 좋아요 모션이 두번 노출
3) 비로그인시 더블클릭시 좋아요 모션 노출
4) 비로그인시
    좋아요클릭 -> 알럿 -> 로그인 -> 최신돌픽으로 이동
---
### 개선 방향
1) 이미지 더블클릭시 좋아요 등록
2) 좋아요 모션 한번 노출
3) 비로그인시 좋아요 모션 노출 X
4) 비로그인시
    좋아요클릭 -> 알럿 -> 로그인 -> 해당 이미지로 다시 이동(좋아요완료)

**Comment by chcjswo** [comment]
수정해서 테스트서버에 올렸으니 테스트 해봐
[테스트 서버 오픈](http://45.62.212.233:4003)

**Comment by moonspam** [comment]
라이브 사이트에서 확인 완료!
