### ISSUE TITLE
알럿 메시지

### ISSUE THREAD

**Issue by chcjswo** [chcjswo/dolpic-nodejs#7]
### 이슈 사항
1) 비로그인시 알럿 팝업 문구가 다름
---
### 개선 방향
1) 알럿 메시지를 "로그인 후 이용가능합니다"로 통일

**Comment by chcjswo** [comment]
수정해서 테스트서버에 올렸으니 테스트 해봐
[테스트 서버 오픈](http://dolpic.chcjswo.xyz)

**Comment by moonspam** [comment]
테스트 서버에서 확인완료!
